config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :pages do
    resource :check, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :last_result, class_name: "Result", optional: true
  has_many :results

  validates :name, presence: true
  validates :url, presence: true
  validates :check_type, presence: true
  validates :selector, presence: true
  validates :match_text, presence: {if: -> { check_type == "text" }}

  def check_and_notify
    check
    last_result.notify
  end



  def check
    scraper = Scraper.new(url)
    result = case check_type
             when "text"
               scraper.text(selector: selector).downcase == match_text.downcase
             when "exists"
               scraper.present?(selector: selector)
             when "not_exists"
               !scraper.present?(selector: selector)
             end
    result = results.create(success: result)
    update(last_result: result)
  end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :page

  def notify
    return unless success?
    UserMailer.with(result: self).success.deliver_later
  end
end

app/models/scraper.rb
require "net/http"

class Scraper
  attr_reader :document

  def initialize(url)
    response = Net::HTTP.get(URI(url))
    @document = Nokogiri::HTML(response)
  end

  def text(selector:)
    document.at_css(selector).text
  end

  def present?(selector:)
    document.at_css(selector).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_page

  def create
    @page.check
    redirect_to @page
  end

  private

  def set_page
    @page = Page.find(params[:page_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.includes(:last_result)
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy!

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:name, :url, :check_type, :selector, :match_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorWebScraper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="max-w-4xl mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, placeholder: "My website" %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.url_field :url, placeholder: "https://example.org/..." %>
  </div>

  <div>
    <%= form.label :check_type, style: "display: block" %>
    <%= form.select :check_type, [["Text", "text"], ["Exists", "exists"], ["Not exists", "not_exists"]] %>
  </div>

  <div>
    <%= form.label :selector, style: "display: block" %>
    <%= form.text_field :selector, placeholder: ".class" %>
  </div>

  <div>
    <%= form.label :match_text, style: "display: block" %>
    <%= form.text_field :match_text, placeholder: "text to match" %>
  </div>

  <div class="mt-4">
    <%= form.submit class: "border border-gray-200 rounded shadow px-2 py-1 hover:bg-gray-100"%>
  </div>
<% end %>

app/views/pages/_page.html.erb
<%= link_to page, id: dom_id(page), class: "p-4 -mx-4 hover:bg-gray-100" do %>
  <div class="flex justify-between">
    <div>
      <h5 class="font-bold"><%= page.name %></h5>
      <div class="text-sm text-gray-700"><%= page.url %></div>
    </div>
    
    <% if page.results.present? %>
      <%= render page.last_result %>
    <% end %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="flex items-center justify-between">
  <h1 class="text-2xl font-bold truncate">
    <%= link_to "‹", @page, class: "p-2 rounded hover:bg-gray-100" %>
    Edit page
  </h1>

  <%= button_to "Delete", @page, method: :delete, class: "border border-gray-200 rounded shadow px-2 py-1 hover:bg-gray-100", data: {turbo_confirm: "Are you sure?"} %>
</div>

<%= render "form", page: @page %>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="flex justify-between">
  <h1 class="text-2xl font-bold">Pages</h1>
  <%= link_to "Monitor a new page", new_page_path, class: "border border-gray-200 rounded shadow px-2 py-1 hover:bg-gray-100" %>
</div>

<div id="pages" class="flex flex-col divide-y divide-gray-200">
  <%= render @pages %>
</div>

app/views/pages/new.html.erb
<h1 class="text-2xl font-bold truncate">
  <%= link_to "‹", root_path, class: "p-2 rounded hover:bg-gray-100" %>
  Monitor a page
</h1>

<%= render "form", page: @page %>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="flex justify-between">
  <h1 class="text-2xl font-bold truncate">
    <%= link_to "‹", root_path, class: "p-2 rounded hover:bg-gray-100" %>
    <%= @page.name %>
  </h1>
  <div>
    <div class="flex gap-1">
      <%= button_to "Run", page_check_path(@page), class: "border border-gray-200 rounded shadow px-2 py-1 hover:bg-gray-100" %>
      <%= link_to "Edit", edit_page_path(@page), class: "border border-gray-200 rounded shadow px-2 py-1 hover:bg-gray-100" %>
    </div>
  </div>
</div>

<%= link_to @page.url, @page.url, class: "text-gray-700", target: :_blank %>

<div class="mt-4">
  <h4 class="font-medium text-gray-700 text-sm">Recent results</h4>
  <%= render @page.results.order(created_at: :desc) %>
</div>

app/views/results/_result.html.erb
<%= tag.div id: dom_id(result), class: "p-1 flex items-center gap-4" do %>
  <div class="w-24 flex gap-1 items-center font-medium">
    <% if result.success? %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4 text-green-500">
        <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14Zm3.844-8.791a.75.75 0 0 0-1.188-.918l-3.7 4.79-1.649-1.833a.75.75 0 1 0-1.114 1.004l2.25 2.5a.75.75 0 0 0 1.15-.043l4.25-5.5Z" clip-rule="evenodd" />
      </svg>
      Success 
    <% else %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4 text-gray-400">
        <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14Zm2.78-4.22a.75.75 0 0 1-1.06 0L8 9.06l-1.72 1.72a.75.75 0 1 1-1.06-1.06L6.94 8 5.22 6.28a.75.75 0 0 1 1.06-1.06L8 6.94l1.72-1.72a.75.75 0 1 1 1.06 1.06L9.06 8l1.72 1.72a.75.75 0 0 1 0 1.06Z" clip-rule="evenodd" />
      </svg>
      Fail
    <% end %>
  </div>
  <div class="text-xs text-gray-700"><%= time_ago_in_words(result.created_at).upcase_first %> ago</div>
<% end %>